### ISSUE TITLE
Run locale models

### ISSUE THREAD

**Issue by user82622** [qwersyk/Newelle#1]
This is an amazing application but it would be so much better if there would be the capability of running locale models, like this censoring is not a problem but mainly "openai" is not getting lists of files and so on.

**Comment by qwersyk** [comment]
Yes, we have plans to add a local version in the future, but currently, we are facing some issues. We need to find a suitable module that will function correctly or undergo proper training, and integrate it effectively into a Flatpak project. Thank you for your feedback; we are delighted that you appreciate our project!
