### ISSUE TITLE
Stop sound buttond and scroll

### ISSUE THREAD

**Issue by dacrhu** [qwersyk/Newelle#108]
If I stop a TTS process with the mute button, the chat scrolling up always.

**Comment by FrancescoCaracciolo** [comment]
It looks like this happens every time the headerbar is edited. This is probably some weird GTK behavior. Didn't manage to fix it tonight.

**Comment by FrancescoCaracciolo** [comment]
I figured out the way to fix it. Apparently when you focus a widget and that is made invisible, everything scrolls up. 
I'm fixing it also for a few other things that cause issues before release. In the meantime you can use CTRL+K to stop the TTS without the chat to scroll

**Comment by dacrhu** [comment]
Thank you!
