### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by chukfinley** [qwersyk/Newelle#2]
ok so i am in a debian vm.
i ran this promt:
![image](https://github.com/qwersyk/Newelle/assets/77645077/a7a8f980-b9a9-46f8-93e6-2db84845eb34)
it worked without any problems.
but than i got this without typing anything:
![image](https://github.com/qwersyk/Newelle/assets/77645077/5a275956-01dd-46cb-b4cb-61bfb9fc62f5)
and this is not the user and the home folder.
Maybe i got the output of someones other promt?!

**Comment by qwersyk** [comment]
We apologize for this bug. Our program uses a preset prompt, which as an example tells how to interact with the user, but neural networks sometimes write not what we expect, this time the neural network used a preset that should not be used at all. In the future, you can disable those functions in the program settings that you do not use. We will try to reduce the chance of such false reports in the future. Thank you for your feedback.
