### ISSUE TITLE
Add Text To Speech (TTS)

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [qwersyk/Newelle#21]
We should add Text To Speech (I would say disabled by default), offering different programs/APIs and languages to choose from as for user preference.
Some of the services/programs we may want to include:
- [ResponsiveVoices](https://responsivevoice.org/)
- espeak
- festival
- VoiceVox
- [gTTS](https://pypi.org/project/gTTS/)

From some programs, it probably is better to just call them outside of flatpak rather than adding more dependencies

**Comment by qwersyk** [comment]
It will be possible to make a simple command entry bar that works like in Foliate.
[![Bildschirmfoto-vom-2023-07-23-09-15-58.png](https://i.postimg.cc/KvjXFXZj/Bildschirmfoto-vom-2023-07-23-09-15-58.png)](https://postimg.cc/rzBZCPR2)

**Comment by FrancescoCaracciolo** [comment]
I already started working on another design, I'm pretty confident that it can be tweaked a bit to get a similar amount of functionality though

**Comment by qwersyk** [comment]
Wow, very cool!!! I didn't want to add a voiceover, but the voiceover is really cool, but I think that some text is better not to voice, such as commands.

**Comment by FrancescoCaracciolo** [comment]
You are right, do you already have a function that recognizes the slices of commands so that I can use it?

**Comment by qwersyk** [comment]
At the moment I'm just cutting out everything in "```" through re(re.sub(r"```.*?```", "", message_label, flags=re.DOTALL))

**Comment by FrancescoCaracciolo** [comment]
Ok nice
