### ISSUE TITLE
Add speech to text

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [qwersyk/Newelle#24]
We can use [SpeechRecognition](https://pypi.org/project/SpeechRecognition/) library that supports a lot of services and looks pretty easy.
To enable speech recognition, we can add a microphone icon to hold or just click near the message box. It would be also nice to add something like keyword recognition to activate it.

**Comment by qwersyk** [comment]
Yeah, It would be very cool if you implement text recognition. I totally agree with everything.
