### ISSUE TITLE
Ability to see which commands will be run beforehand

### ISSUE THREAD

**Issue by KirrimK** [qwersyk/Newelle#3]
Hello,

I just discovered this project and I think it's really cool.

The ability to run commands using the flatpak sandbox is really nice, but do you think it would be possible to have the option to see what command will be run in the console before clicking on a button to validate/cancel it?

It might be nice for people running commands without a sandbox, or just to check what is happening with the model (I'm sure nobody likes to get a `rm -rf /` or a fork bomb prompt-injected into their console, even in a sandbox).

Thanks again for the hard work!

**Comment by qwersyk** [comment]
Thank you for your feedback, I think you're right, in future versions I will try to add a blacklist of commands, as well as the ability to turn off auto-start commands, we appreciate your feedback, we are glad you like our product!
