### ISSUE TITLE
Gradually generate text (Token streaming)

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [qwersyk/Newelle#34]
Since some services support it, it would be a nice thing to add, specially for local language models that generate text in a pretty slow way

**Comment by qwersyk** [comment]
I tried to implement this, it is real, but I noticed that if you send a message and generate to the end, or generate by token, the speed of writing messages is very different, maybe I am wrong, but a normal message was written 30 seconds, and generate by token, about 8 minutes, maybe I did not use the function correctly.

**Comment by qwersyk** [comment]
https://streamable.com/e/v5q7lx?autoplay=1
But it looks really good!
If it works speed-wise normally, I'm all for it!

**Comment by FrancescoCaracciolo** [comment]
The problem is with bai chat or gtk updating the message?

**Comment by qwersyk** [comment]
Well I'm talking about the local model, I haven't tried it with baichat, because I don't know if it's possible to realize it with baichat.

**Comment by FrancescoCaracciolo** [comment]
In being possible it should be possible, I don't know with the current module. But we also have other language model services that support it already.

You might want to try with others, at least to check if it is a GTK thing, a thing of the model or a problem with the implementation

**Comment by qwersyk** [comment]
Hmm. It'd be cool to do that, actually. There is no problem with Gtk in this.

**Comment by FrancescoCaracciolo** [comment]
You might want to try it with Poe. Here is an [example](https://github.com/ading2210/poe-api#sending-messages) of how to do that.
