### ISSUE TITLE
[Feature Request] Implement BAI Chat API Key support.

### ISSUE THREAD

**Issue by programminglynx** [qwersyk/Newelle#39]
**Suggestion/Bug Fix**

**Proposal** : Implement a system to allow BAI Chat to be connected to via an API Key.

**Explanation** : This would fix the current issues with BAI Chat and open the way to changing the BAI Chat model in the future.
I am currently unable to find the name of the BAI-Chat free model (and I am unsure if it even exists) in the BAI Chat documentation ([https://docs.theb.ai/quickstart](https://docs.theb.ai/quickstart)) but believe that adding API functionality will be beneficial in the future, particularly if we also were to implement the ability to choose the model.

_(I will be trying to learn how to implement this myself but it will be a long time before I can manage such a thing. Thank you for making such an amazing project!)_

**Comment by FrancescoCaracciolo** [comment]
We have added a new modular way to add new peoviders and models, though I haven't documented it yet. I will try to document it soon so that it will be quite easy for you or anyone else to implement it

**Comment by FrancescoCaracciolo** [comment]
You can now use OpeanAI handler with "https://api.theb.ai/v1/" as endpoint and your api key
