### ISSUE TITLE
Request to enable snap support

### ISSUE THREAD

**Issue by soumyaDghosh** [qwersyk/Newelle#4]
There are many hardcoded path in this app, which works only with snaps. Kindly generalise them and enable support for other packaging formats like snap. Patching them is often tough, cause we need to update the patch also with each release. Also, the `flatpak spwan` command is used which is unnecessary for Snaps.

**Comment by qwersyk** [comment]
I don't know much about snap, but in future versions I will try to make porting to snap packages easier. Thank you for your efforts in keeping our application on snap packs.

**Comment by qwersyk** [comment]
> I created a [new branch](https://github.com/qwersyk/Newelle/tree/snap) for snap for easier work, hope this helps, also we sent you an [invitation](https://github.com/qwersyk/Newelle/invitations) to collaborate

**Comment by soumyaDghosh** [comment]
Hii, sorry, I was a little busy these days. But, would like to discuss with you regarding this. Is there any way to directly contact with you?

**Comment by qwersyk** [comment]
Yes, of course, I'm on telegram: @qwersym
