### ISSUE TITLE
Chat not usable on ChromeOS's Debian

### ISSUE THREAD

**Issue by Huge** [qwersyk/Newelle#40]
Installed on Linux on ChromeOS, that chat is deadly white, the menus seem fine.
![Screenshot 2023-09-08 11 27 58](https://github.com/qwersyk/Newelle/assets/111648/8f6374e6-3be7-4696-bc6d-801a11a8b066)

Can you please try to fix it? That would be worth a coffee.')

**Comment by FrancescoCaracciolo** [comment]
I think that it is actually how it should look. The bottom part is where you write

**Comment by FrancescoCaracciolo** [comment]
Do you still have problems with the new version?
