### ISSUE TITLE
Problems with Newelle on Vanilla OS 2 Orchid

### ISSUE THREAD

**Issue by RaulKong898** [qwersyk/Newelle#45]
Hello qwersyk,

I'm writing to let you know about a problem I'm having with the Newelle app on Vanilla OS 2 Orchid.

Your application is extremely useful for Linux users, providing a wide range of functions, including file creation, system management, and Python code execution. However, I ran into a bug that prevents me from sending messages to the bot.

I have attached a screenshot of that error. I would appreciate it if you could investigate this issue and implement a solution as soon as possible.

I would also like to suggest better integration of Newelle with Vanilla OS 2 Orchid. The documentation available at https://docs.vanillaos.org/ could be a valuable resource to facilitate this integration.

I strongly believe that Newelle has the potential to be an exceptional virtual assistant for Linux users. With its unique extensions and advanced features, Newelle differentiates itself significantly from other available options.

I would like to request that you consider the following improvements:

* Update Prioritization: Ensuring periodic updates to keep Newelle compatible with the latest versions of Vanilla OS.
* Optimization for Vanilla OS: Adapting Newelle to the specifics of Vanilla OS 2 Orchid, providing a smoother and more integrated user experience.
* Implementation of Advanced Commands: Extending Newelle functionality to include Vanilla OS specific commands such as power management, network configuration and peripheral device control.

I am convinced that implementing these suggestions will help strengthen Newelle's position as an essential tool for Linux users, providing them with a complete and intuitive solution for interacting with their operating system.

Thank you for your time and attention. I look forward to solving the problem with sending messages and implementing the suggested improvements.

Regards,
Raul Popescu

**Comment by RaulKong898** [comment]
I would also like to recommend a new suggestion: Use twins. It is the ai from google and it is very good for the application.

**Comment by RaulKong898** [comment]
I would also like to recommend a new suggestion: Use Gemini AI. It's Google's AI and it's very good for the app.

**Comment by FrancescoCaracciolo** [comment]
At the moment I can't work on Newelle, I will probably continue during this summer, I don't know for @qwersyk

**Comment by FrancescoCaracciolo** [comment]
Added Gemini support and changed defaults
