### ISSUE TITLE
Allowing to load custom local models

### ISSUE THREAD

**Issue by FrancescoCaracciolo** [qwersyk/Newelle#57]
Loading custom models in GPT4All is possible, here is the [guide](https://github.com/nomic-ai/gpt4all/wiki/Configuring-Custom-Models).
We should implement a way to do it.

**Comment by dtfleetwood** [comment]
This is where I would onboard to this app. Privacy/security is what is lacking in using online models.

**Comment by renarzamora** [comment]
Could someone attach this model:gpt-oss-20b?
