### ISSUE TITLE
Compatibility with Ollama

### ISSUE THREAD

**Issue by Froggy232** [qwersyk/Newelle#72]
Hi,
Would it be possible to add compatibility with self hosted ollama instance?
Thanks for your software,
Have a nice day

**Comment by FrancescoCaracciolo** [comment]
Hello, I think you can already use it.
Use OpenAI API, as endpoint put something like http://localhost:11434/v1/ , so instance/v1/. Be sure to put an API key, then adjust the other parameters at your preference.

Tell us if it worked!

**Comment by Froggy232** [comment]
Thanks, I will try ASAP and report back!

**Comment by Froggy232** [comment]
Sorry, it doesn't seems to work, I have put a screenshot of my settings here : 
![Capture d’écran du 2024-08-24 20-34-12](https://github.com/user-attachments/assets/ac4b839b-2e0c-4bd8-b493-9db523f72abd)
Please note that I don't have API key in my ollama instance, I have put a random string.
Thanks you again!

**Comment by FrancescoCaracciolo** [comment]
Just to be sure, is the endpoint exactly "http://localhost:11434/v1/"?

**Comment by Froggy232** [comment]
Yes, it's exactly like that.
It's not a big deal though, I can simply deploy localai, rely it to my ollama instance and it should work right?
Thanks you again for your work.
Have a nice day!

**Comment by FrancescoCaracciolo** [comment]
Anything that supports openai interference api should work fine

**Comment by Froggy232** [comment]
Nice, thanks you a lot, I will go this way.
