### ISSUE TITLE
Flatseal instruction confusing

### ISSUE THREAD

**Issue by munmuni** [qwersyk/Newelle#74]
where to add the org.freedesktop.flatpak thing

also "Session Bus" is in two places: 
![image](https://github.com/user-attachments/assets/99630ab1-d8f8-42ad-8d6c-ceb583fc9bbe)

and DBus Session Bus: 
![image](https://github.com/user-attachments/assets/32b970c5-06cd-4163-8e17-b6a35480deb7)

**Comment by qwersyk** [comment]
Hello, thank you and sorry for the confusion. There is a [review](https://fostips.com/newelle-ai-chatbot-interact-system/?amp=1), although it is outdated, but hopefully it will make sense to you. 

![image](https://fostips.com/wp-content/uploads/2023/07/newelle-terminal-permission-1.webp)

I will also warn you to be careful when using this, this way you are basically disabling virtualization and the chat can harm your system.
