### ISSUE TITLE
No "Ollama Instance" option in the preferences window

### ISSUE THREAD

**Issue by K0-RR** [qwersyk/Newelle#79]
According to https://github.com/qwersyk/Newelle/wiki/User-guide-to-the-available-LLMs#use-ollama-instance-in-newelle.

![Screenshot from 2024-09-26 14-00-24](https://github.com/user-attachments/assets/5020645d-c700-428b-9d9f-dbc7ec7df4dc)

**Comment by FrancescoCaracciolo** [comment]
It's because it has not been released yet. It is available in the source code

**Comment by FrancescoCaracciolo** [comment]
It is now available on Flathub version
