### ISSUE TITLE
Output is duplicated

### ISSUE THREAD

**Issue by amminadabz** [qwersyk/Newelle#89]
Using GPT 3.5, Newelle version 0.3.1 on Ultramarine (Fedora) 40.

![image](https://github.com/user-attachments/assets/053353d3-6c12-4c2d-a2a9-4ad17cd4f57e)

**Comment by FrancescoCaracciolo** [comment]
Plese read https://github.com/qwersyk/Newelle/wiki/User-guide-to-the-available-LLMs.

This is not a bug on our side
